version: '3.8'

services:
  next:
    container_name: next
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - POSTGRES_URL=postgres://nextjs:nextjs@nextdb:5432/nextjs
    networks:
      - next
    depends_on:
      nextdb:
        condition: service_healthy

  nextdb:
    build:
      context: ./containers/pgsql
      dockerfile: Dockerfile
    container_name: nextdb
    restart: always
    environment:
      POSTGRES_DB: nextjs
      POSTGRES_USER: nextjs
      POSTGRES_PASSWORD: nextjs
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./containers/pgsql/init.sh/:/docker-entrypoint-initdb.d/
    networks:
      - next
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U nextjs -d nextdb" ]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  next:
    driver: bridge
